### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by beneyal** [the-deep-learners/TensorFlow-LiveLessons#1]
I'd like to share my experience with installing TensorFlow on Windows, which was actually a piece of cake since the 1.0 release. I thought about making a pull-request, but maybe you have your reasons for not elaborating.

Probably the most important part for any Windows user is to download a Python distribution which already has built-in support for the scientific Python stack. I used Anaconda, but there are WinPython and Enthought Canopy (for Python 3). From there, it's just following the instructions at [TensorFlow's page](https://www.tensorflow.org/install/install_windows).

In short, given Anaconda is installed and in the user's path (happens by default):
```
C:\> conda create -n tf python=3.5
...
C:\> activate tf
(tf) C:\> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.1-cp35-cp35m-win_amd64.whl
...
(tf) C:\> conda install jupyter matplotlib (etc.)
```

To use TF with a GPU, the headache is more from the CUDA side, but not too much:

1. Install Visual Studio Community 2015, making sure C++ is part of the installation.
2. Install CUDA 8
3. Download cuDNN 5.1 (which **isn't** the latest version) and drop the files from the zip into where you installed CUDA.
4. Same instructions as above, but use `https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.2.1-cp35-cp35m-win_amd64.whl` instead.

Hope this helps :smiley:

**Comment by jonkrohn** [comment]
This is tremendously helpful, @beneyal -- thank you! Please feel free to make a pull request to integrate these Windows instructions with my existing ones.

**Comment by jonkrohn** [comment]
@beneyal has resolved the issue he raised :1st_place_medal:

**Comment by anderl80** [comment]
Shouldn't it be the other way round? If you install a specific tf package using pip within anaconda and then install keras (with its dependencies), the specific tf package will be overwritten. Or do I have a wring perception of this?

**Comment by jonkrohn** [comment]
Hi @anderl80, installing Keras does not overwrite your installation of TensorFlow.

**Comment by anderl80** [comment]
Hi @jonkron unfortunatly my Anaconda did overwrite. I used the GUI installation but I think calling conda install from CLI will resolve the same dependencies. Anyhow did work in the endet. Looking forward for the live sessions!!

**Comment by jonkrohn** [comment]
Oh, I see, @anderl80. That is news to me -- good to know! Looking forward to having you in class this week 😃
