### ISSUE TITLE
Jupyter conflict with Tornado or Ipykernal?  GPU version container 

### ISSUE THREAD

**Issue by JohnKruse** [the-deep-learners/TensorFlow-LiveLessons#16]
I'm receiving the error below when I access a Jupyter notebook when I run the GPU container (I can run the non-GPU container without a hitch). The notebook will have a flashing blue "Connected" button next to the Trusted/Not Trusted button in the command bar at the top.
When I try to execute a line, it just stays with the asterisk rather than a number showing that it has successfully executed.
I Googled it and have found that this bug was a known problem with Tornado and Jupyter (https://github.com/jupyter/help/issues/272) but I don't see Tornado in the Dockerfile, and I've tried rolling back to older versions on my Linux box (Ubuntu 16.04) thinking that I might not be understanding the nature of the problem. Others in the link found a solution in rolling back "ipykernel from 4.8.0 to 4.6.0". I also don't see ipykernal, but I guess it could be embedded in one of the other packages.
THanks, John 

HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/f97fd50a-35a7-42b7-a58c-d3d7492141f2/channels?session_id=E2DB76BABC4C4B578FA8609CE7C119C4', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 262, in open
        super(ZMQChannelsHandler, self).open()
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 176, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'

**Comment by jonkrohn** [comment]
Hi @JohnKruse, yeah, this can be annoying. At my company, we've seen this problem occur when people `pip install` a new library that updates some older version of a library like Tornado within the container. Can you try re-building a fresh container from the image and see if everything's hunky-dory?
