### ISSUE TITLE
How-to change base_url for jupyter notebooks?

### ISSUE THREAD

**Issue by JayTeeSF** [the-deep-learners/TensorFlow-LiveLessons#18]
Heya Jon,
First, thanks for all the great lessons (I’m working through your videos on Safaribooks; great stuff)!

If you don’t mind my asking what’s the simplest way to force this docker instance to use a different base_url, so I can proxy this page via the main app-server in my test-env?

Cheers!

sorry, nm:
```sudo docker run --entrypoint "/opt/conda/bin/jupyter-notebook" -v /data/TensorFlow-LiveLessons:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack --NotebookApp.base_url=/admin/jupyter```

**Comment by JayTeeSF** [comment]
sorry; nm: ```sudo docker run --entrypoint "/opt/conda/bin/jupyter-notebook" -v /data/TensorFlow-LiveLessons:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack --NotebookApp.base_url=/my/prefix```

**Comment by jonkrohn** [comment]
Glad you're enjoying the LiveLessons, @JayTeeSF and that you were able to resolve this issue :)
