### ISSUE TITLE
intermediate_net_in_tensorflow

### ISSUE THREAD

**Issue by jhagege** [the-deep-learners/TensorFlow-LiveLessons#20]
Maybe a trivial question, but I don't understand why do we "fetch" the optimizer. 
```
# feed batch data to run optimization and fetching cost and accuracy: 
 _, batch_cost, batch_acc = session.run([optimizer, cost, accuracy_pct], 
                                         feed_dict={x: batch_x, y: batch_y})
```

Happy to hear your thoughts about this. 
Thanks !

**Comment by jonkrohn** [comment]
lol @jhagege -- that's not really a code issue is it? 

In any event: We call `optimizer` to ensure that it runs within the session. It doesn't have any useful output, however, so we pass it into `_`.

**Comment by jhagege** [comment]
Did not find a better way to ask you a question on safaribooksonline :) 
In any case, thanks, very helpful !

**Comment by jonkrohn** [comment]
😉
