### ISSUE TITLE
unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by aeldemerdash** [the-deep-learners/TensorFlow-LiveLessons#21]
When I write "sudo docker build -t tensorflow-ll-stack ." I getting the below "unauthorized: incorrect username or password " Error.   

Sending build context to Docker daemon  5.877MB
Step 1/9 : FROM jupyter/scipy-notebook
Get https://registry-1.docker.io/v2/jupyter/scipy-notebook/manifests/latest: unauthorized: incorrect username or password

**Comment by jonkrohn** [comment]
Hey there @aeldemerdash -- do you have `sudo` permission on your system?
