### ISSUE TITLE
cannot build the docker file in windows

### ISSUE THREAD

**Issue by mohamadk** [the-deep-learners/TensorFlow-LiveLessons#23]
Hi I want to build [the docker file](https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/Dockerfile) in windows But I get this error    

```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::seaborn==0.9.0=py_0
  - conda-forge/linux-64::matplotlib==3.0.3=py37_1
failed

SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs:
    - tensorflow=1.0
  pinned specs:
    - python=3.7
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
/opt/conda/conda-meta/pinned.


The command '/bin/sh -c conda install --quiet --yes 'tensorflow=1.0*'' returned a non-zero code: 1
```
can you help me with this?

**Comment by jonkrohn** [comment]
Hi @mohamadk -- I'm afraid I don't have access to a Windows machine so I might not be able to help out much. That said, however, what version of Windows are you using? I think Docker may only work properly on Windows 10 Professional. If you have another version try one of the alternative installations provided here: https://github.com/the-deep-learners/TensorFlow-LiveLessons/tree/master/installation#windows

**Comment by mohamadk** [comment]
I'm using Win10 Pro.

**Comment by jonkrohn** [comment]
Hmm, yeah, I'm afraid I'm not sure what's wrong then. Perhaps try StackOverflow? Another option that I'm beginning to use in my live trainings is to use Google Colab, which I'm really happy with and should support all of my TensorFlow LiveLessons notebooks: https://colab.research.google.com/

**Comment by jonkrohn** [comment]
Hi @mohamadk -- I'm reopening this issue. Another user -- on ubuntu -- identified a similar problem so I think it's a general one, not a Win10 Pro-specific one.

**Comment by jonkrohn** [comment]
Ok @mohamadk -- I think I've resolved the issue by specifying a Docker container tag. 

Could you please `git pull` the latest Dockerfile and try building again?

**Comment by mohamadk** [comment]
sure, I let you know as soon as I try it.

**Comment by mohamadk** [comment]
the environment inconsistent error disappeared but it shows the new error

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oc3kxmi9/gensim/
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install gensim==2.3.0' returned a non-zero code: 1
```

**Comment by jonkrohn** [comment]
Hmm, curious. The new Dockerfile builds without issue for me on ubuntu. Could you please provide me with the full output from the failing Docker build? It'd be helpful to know which step this is failing at, for example.

**Comment by mohamadk** [comment]
here is the full error

```
docker build -t tensorflow-ll-stack .
Sending build context to Docker daemon  5.945MB
Step 1/9 : FROM jupyter/scipy-notebook:e7000ca1416d
 ---> 07b62729a953
Step 2/9 : MAINTAINER Jon Krohn <jon@untapt.com>
 ---> Using cache
 ---> 8a2999461965
Step 3/9 : USER $NB_USER
 ---> Using cache
 ---> 9f09003b8b3c
Step 4/9 : RUN pip install --ignore-installed --upgrade tensorflow==1.9
 ---> Using cache
 ---> c853b3960f02
Step 5/9 : RUN pip install tflearn==0.3.2
 ---> Using cache
 ---> 942491707718
Step 6/9 : RUN pip install keras==2.0.8
 ---> Using cache
 ---> 1868fb6d953e
Step 7/9 : RUN pip install nltk==3.2.4
 ---> Using cache
 ---> c685f57b76e8
Step 8/9 : RUN pip install gensim==2.3.0
 ---> Running in 3d2dc3ec0659
Collecting gensim==2.3.0
  Downloading https://files.pythonhosted.org/packages/bc/ed/fbbb2cc3f37a39cc4ff8e5f667374478fb852b384840aa7feb9608144290/gensim-2.3.0.tar.gz (17.2MB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/gensim.egg-info
    writing pip-egg-info/gensim.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/gensim.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/gensim.egg-info/requires.txt
    writing top-level names to pip-egg-info/gensim.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/gensim.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-utttkt9q/gensim/setup.py", line 302, in <module>
        include_package_data=True,
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-utttkt9q/gensim/setup.py", line 100, in finalize_options
        import numpy
      File "/opt/conda/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/opt/conda/lib/python3.6/site-packages/numpy/core/__init__.py", line 91, in <module>
        raise ImportError(msg.format(path))
    ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/opt/conda/lib/python3.6/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-utttkt9q/gensim/
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install gensim==2.3.0' returned a non-zero code: 1

```

**Comment by jonkrohn** [comment]
This is most helpful, @mohamadk -- thanks! I don't get the error (see below) but I'm going to make some updates to the Dockerfile now that might fix your issue anyway. Give me a few minutes.

`sudo docker build -t tensorflow-ll-stack . 
Sending build context to Docker daemon  357.3MB
Step 1/9 : FROM jupyter/scipy-notebook:e7000ca1416d
e7000ca1416d: Pulling from jupyter/scipy-notebook
a48c500ed24e: Pull complete 
1e1de00ff7e1: Pull complete 
0330ca45a200: Pull complete 
471db38bcfbf: Pull complete 
0b4aba487617: Pull complete 
730fa79a87e1: Pull complete 
9a1a2a0601f1: Pull complete 
e573f4f810fd: Pull complete 
b1adcddb94b3: Pull complete 
fbae0d28d3e8: Pull complete 
340d8fe7f9dd: Pull complete 
8463439e4771: Pull complete 
b58fe29acb40: Pull complete 
a6adc137ae8e: Pull complete 
148eea211ca9: Pull complete 
1643129dd1c3: Pull complete 
9793e058f364: Pull complete 
c76333cf1455: Pull complete 
1cef9f64927d: Pull complete 
1bc75d625a5e: Pull complete 
6310b3759a8e: Pull complete 
49720a943f4d: Pull complete 
16cce698c4fe: Pull complete 
Digest: sha256:3f96e9cf0fbdb64a4cfbb11b2a6f9f97f6ecc56b117553fca3e05e5c3f3323e2
Status: Downloaded newer image for jupyter/scipy-notebook:e7000ca1416d
 ---> 07b62729a953
Step 2/9 : MAINTAINER Jon Krohn <jon@untapt.com>
 ---> Running in a5ebf29e30e1
 ---> 7383e7d969eb
Removing intermediate container a5ebf29e30e1
Step 3/9 : USER $NB_USER
 ---> Running in b0004e89cc90
 ---> a928cd930c49
Removing intermediate container b0004e89cc90
Step 4/9 : RUN conda install --quiet --yes 'tensorflow=1.0*'
 ---> Running in 5c0389a3744d
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs: 
    - tensorflow=1.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.0.1                |py36_nomklh9d22d0a_0        17.8 MB  defaults
    libopenblas-0.2.20         |       h9ac9557_7         8.8 MB  defaults
    libgcc-ng-8.2.0            |       hdf63c60_1         7.6 MB  defaults
    sqlite-3.26.0              |    h67949de_1001         1.9 MB  conda-forge
    liblapacke-3.8.0           |       8_openblas           6 KB  conda-forge
    mock-3.0.5                 |           py36_0          44 KB  conda-forge
    openblas-0.3.6             |       h6e990d7_1        15.8 MB  conda-forge
    certifi-2019.3.9           |           py36_0         149 KB  conda-forge
    numpy-1.11.3               |py36he5ce36f_1207         3.6 MB  conda-forge
    ca-certificates-2019.3.9   |       hecc5488_0         146 KB  conda-forge
    libgfortran-ng-7.3.0       |       hdf63c60_0         1.3 MB  defaults
    tensorflow-1.0.0           |           py36_0        35.1 MB  conda-forge
    readline-7.0               |    hf8c457e_1001         391 KB  conda-forge
    blas-2.8                   |         openblas           6 KB  conda-forge
    libcblas-3.8.0             |       8_openblas           6 KB  conda-forge
    openssl-1.1.1b             |       h14c3975_1         4.0 MB  conda-forge
    tk-8.6.9                   |    h84994c4_1001         3.2 MB  conda-forge
    scikit-learn-0.19.1        |py36_nomklh27f7947_0         5.2 MB  defaults
    xz-5.2.4                   |    h14c3975_1001         366 KB  conda-forge
    liblapack-3.8.0            |       8_openblas           6 KB  conda-forge
    libblas-3.8.0              |       8_openblas           6 KB  conda-forge
    libstdcxx-ng-8.2.0         |       hdf63c60_1         2.9 MB  defaults
    python-3.6.7               |    h381d211_1004        34.5 MB  conda-forge
    ncurses-6.1                |    hf484d3e_1002         1.3 MB  conda-forge
    libedit-3.1.20170329       |    hf8c457e_1001         172 KB  conda-forge
    cryptography-2.6.1         |   py36h72c5cf5_0         606 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       144.9 MB

The following NEW packages will be INSTALLED:

    libblas:         3.8.0-8_openblas              conda-forge
    libcblas:        3.8.0-8_openblas              conda-forge
    libgfortran-ng:  7.3.0-hdf63c60_0              defaults   
    liblapack:       3.8.0-8_openblas              conda-forge
    liblapacke:      3.8.0-8_openblas              conda-forge
    libopenblas:     0.2.20-h9ac9557_7             defaults   
    mock:            3.0.5-py36_0                  conda-forge
    tensorflow:      1.0.0-py36_0                  conda-forge

The following packages will be UPDATED:

    blas:            1.1-openblas                  conda-forge --> 2.8-openblas                conda-forge
    ca-certificates: 2018.4.16-0                   conda-forge --> 2019.3.9-hecc5488_0         conda-forge
    certifi:         2018.4.16-py36_0              conda-forge --> 2019.3.9-py36_0             conda-forge
    cryptography:    2.2.1-py36_0                  conda-forge --> 2.6.1-py36h72c5cf5_0        conda-forge
    libedit:         3.1.20170329-0                conda-forge --> 3.1.20170329-hf8c457e_1001  conda-forge
    libgcc-ng:       7.2.0-hdf63c60_3              defaults    --> 8.2.0-hdf63c60_1            defaults   
    libstdcxx-ng:    7.2.0-hdf63c60_3              defaults    --> 8.2.0-hdf63c60_1            defaults   
    ncurses:         5.9-10                        conda-forge --> 6.1-hf484d3e_1002           conda-forge
    openblas:        0.2.20-8                      conda-forge --> 0.3.6-h6e990d7_1            conda-forge
    openssl:         1.0.2o-0                      conda-forge --> 1.1.1b-h14c3975_1           conda-forge
    python:          3.6.5-1                       conda-forge --> 3.6.7-h381d211_1004         conda-forge
    readline:        7.0-0                         conda-forge --> 7.0-hf8c457e_1001           conda-forge
    sqlite:          3.20.1-2                      conda-forge --> 3.26.0-h67949de_1001        conda-forge
    tk:              8.6.7-0                       conda-forge --> 8.6.9-h84994c4_1001         conda-forge
    xz:              5.2.3-0                       conda-forge --> 5.2.4-h14c3975_1001         conda-forge

The following packages will be DOWNGRADED:

    numpy:           1.13.3-py36_blas_openblas_201 conda-forge [blas_openblas] --> 1.11.3-py36he5ce36f_1207    conda-forge
    scikit-learn:    0.19.1-py36_blas_openblas_201 conda-forge [blas_openblas] --> 0.19.1-py36_nomklh27f7947_0 defaults   
    scipy:           1.0.1-py36_blas_openblas_200  conda-forge [blas_openblas] --> 1.0.1-py36_nomklh9d22d0a_0  defaults   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
 ---> 1130b3f30817
Removing intermediate container 5c0389a3744d
Step 5/9 : RUN pip install tflearn==0.3.2
 ---> Running in d999ccc03fe4
Collecting tflearn==0.3.2
  Downloading https://files.pythonhosted.org/packages/16/ec/e9ce1b52e71f6dff3bd944f020cef7140779e783ab27512ea7c7275ddee5/tflearn-0.3.2.tar.gz (98kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.6/site-packages (from tflearn==0.3.2)
Building wheels for collected packages: tflearn
  Running setup.py bdist_wheel for tflearn: started
  Running setup.py bdist_wheel for tflearn: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/d0/f6/69/0ef3ee395aac2e5d15d89efd29a9a216f3c27767b43b72c006
Successfully built tflearn
Installing collected packages: tflearn
Successfully installed tflearn-0.3.2
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 50557ea991bc
Removing intermediate container d999ccc03fe4
Step 6/9 : RUN pip install keras==2.0.8
 ---> Running in f68a820e79b3
Collecting keras==2.0.8
  Downloading https://files.pythonhosted.org/packages/67/3f/d117d6e48b19fb9589369f4bdbe883aa88943f8bb4a850559ea5c546fefb/Keras-2.0.8-py2.py3-none-any.whl (276kB)
Requirement already satisfied: scipy>=0.14 in /opt/conda/lib/python3.6/site-packages (from keras==2.0.8)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.6/site-packages (from keras==2.0.8)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.6/site-packages (from keras==2.0.8)
Requirement already satisfied: numpy>=1.9.1 in /opt/conda/lib/python3.6/site-packages (from keras==2.0.8)
Installing collected packages: keras
Successfully installed keras-2.0.8
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 96ef26636861
Removing intermediate container f68a820e79b3
Step 7/9 : RUN pip install nltk==3.2.4
 ---> Running in a48b4b3ba502
Collecting nltk==3.2.4
  Downloading https://files.pythonhosted.org/packages/cd/c2/858e0708b497116ae45cf5c6b1f66984ac60729c61e49df6c1c0b808d1e4/nltk-3.2.4.tar.gz (1.2MB)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from nltk==3.2.4)
Building wheels for collected packages: nltk
  Running setup.py bdist_wheel for nltk: started
  Running setup.py bdist_wheel for nltk: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/36/f1/5c/f667347d86a3a534ba4c0127eed4389f929916e3ec88bb461a
Successfully built nltk
Installing collected packages: nltk
Successfully installed nltk-3.2.4
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 1dd7644a5ad4
Removing intermediate container a48b4b3ba502
Step 8/9 : RUN pip install gensim==2.3.0
 ---> Running in 8a3341f1cf7f
Collecting gensim==2.3.0
  Downloading https://files.pythonhosted.org/packages/bc/ed/fbbb2cc3f37a39cc4ff8e5f667374478fb852b384840aa7feb9608144290/gensim-2.3.0.tar.gz (17.2MB)
Requirement already satisfied: numpy>=1.11.3 in /opt/conda/lib/python3.6/site-packages (from gensim==2.3.0)
Requirement already satisfied: scipy>=0.18.1 in /opt/conda/lib/python3.6/site-packages (from gensim==2.3.0)
Requirement already satisfied: six>=1.5.0 in /opt/conda/lib/python3.6/site-packages (from gensim==2.3.0)
Collecting smart_open>=1.2.1 (from gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/bf/ba/7eaf3c0dbe601c43d88e449dcd7b61d385fe07c0167163f63f58ece7c1b5/smart_open-1.8.3.tar.gz (60kB)
Collecting boto>=2.32 (from smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/23/10/c0b78c27298029e4454a472a1919bde20cb182dab1662cec7f2ca1dcc523/boto-2.49.0-py2.py3-none-any.whl (1.4MB)
Requirement already satisfied: requests in /opt/conda/lib/python3.6/site-packages (from smart_open>=1.2.1->gensim==2.3.0)
Collecting boto3 (from smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/73/80/1ccde5e54cae72b572ff830fe43ac2578f8f20160ba52ef0e9919b9e5966/boto3-1.9.144-py2.py3-none-any.whl (128kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests->smart_open>=1.2.1->gensim==2.3.0)
Requirement already satisfied: idna<2.7,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests->smart_open>=1.2.1->gensim==2.3.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests->smart_open>=1.2.1->gensim==2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests->smart_open>=1.2.1->gensim==2.3.0)
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3->smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/d7/de/5737f602e22073ecbded7a0c590707085e154e32b68d86545dcc31004c02/s3transfer-0.2.0-py2.py3-none-any.whl (69kB)
Collecting botocore<1.13.0,>=1.12.144 (from boto3->smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/0c/97/8f1b2bb354186911d62972d5bb18c87bf56faee523a87980222beb314f23/botocore-1.12.144-py2.py3-none-any.whl (5.4MB)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /opt/conda/lib/python3.6/site-packages (from botocore<1.13.0,>=1.12.144->boto3->smart_open>=1.2.1->gensim==2.3.0)
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.144->boto3->smart_open>=1.2.1->gensim==2.3.0)
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
Building wheels for collected packages: gensim, smart-open
  Running setup.py bdist_wheel for gensim: started
  Running setup.py bdist_wheel for gensim: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/3a/1f/86/63c886325bdffa379a7c91499bc9ea6317a4e4e0fc6e2ff1ce
  Running setup.py bdist_wheel for smart-open: started
  Running setup.py bdist_wheel for smart-open: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/b8/cb/43/c0ba52baf2b0e371ec1d5b2d4685d6d24617b1391f3eeacda5
Successfully built gensim smart-open
Installing collected packages: boto, docutils, jmespath, botocore, s3transfer, boto3, smart-open, gensim
Successfully installed boto-2.49.0 boto3-1.9.144 botocore-1.12.144 docutils-0.14 gensim-2.3.0 jmespath-0.9.4 s3transfer-0.2.0 smart-open-1.8.3
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> a6bde728229a
Removing intermediate container 8a3341f1cf7f
Step 9/9 : RUN pip install gym==0.9.4
 ---> Running in bc52c637b94d
Collecting gym==0.9.4
  Downloading https://files.pythonhosted.org/packages/f8/9f/b50f4c04a97e316ebfccae3104e5edbfe7bc1c687ee9ebeca6fa6343d197/gym-0.9.4.tar.gz (157kB)
Requirement already satisfied: numpy>=1.10.4 in /opt/conda/lib/python3.6/site-packages (from gym==0.9.4)
Requirement already satisfied: requests>=2.0 in /opt/conda/lib/python3.6/site-packages (from gym==0.9.4)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from gym==0.9.4)
Collecting pyglet>=1.2.0 (from gym==0.9.4)
  Downloading https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl (1.0MB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests>=2.0->gym==0.9.4)
Requirement already satisfied: idna<2.7,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests>=2.0->gym==0.9.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests>=2.0->gym==0.9.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests>=2.0->gym==0.9.4)
Collecting future (from pyglet>=1.2.0->gym==0.9.4)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
Building wheels for collected packages: gym, future
  Running setup.py bdist_wheel for gym: started
  Running setup.py bdist_wheel for gym: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/2f/ae/a0/126678adc5f1f8905309a4712ea29537999787f610edbcb0a4
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /home/jovyan/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built gym future
Installing collected packages: future, pyglet, gym
Successfully installed future-0.17.1 gym-0.9.4 pyglet-1.3.2
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 6f335ceb31ed
Removing intermediate container bc52c637b94d
Successfully built 6f335ceb31ed
Successfully tagged tensorflow-ll-stack:latest`

**Comment by jonkrohn** [comment]
Wait a second... @mohamadk -- why is your step 4 different from mine? In my Dockerfile, I use `conda install` of TensorFlow 1.0, but in yours I see `pip install` of TensorFlow 1.9! I suspect this is the source of your issue. Please revert to my Dockerfile and see if the container builds properly.

**Comment by mohamadk** [comment]
sorry I changed the docker file. 
after a complete new clone, my problem solved. thanks for your help.

**Comment by jonkrohn** [comment]
Great, I'm glad that worked! By the way, I think the line you added might have worked if you dropped the `--ignore-installed` flag although I haven't tested this.
