### ISSUE TITLE
this container no longer works

### ISSUE THREAD

**Issue by noiseoverip** [the-deep-learners/TensorFlow-LiveLessons#26]
for whatever reasons jupyter is not installed in it:

Executing the command: jupyter notebook
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
ImportError: No module named notebook.notebookapp

**Comment by noiseoverip** [comment]
sorry, didn't see your response... i will send you details later today, i am was as surprised as you are (due to elicit versions in docker file) but didn't have time to look into it more closely

**Comment by noiseoverip** [comment]
so i listed packages on original container: 
```
docker run -it --rm jupyter/scipy-notebook:e7000ca1416d /bin/bash -c "pip list | grep jupyter"
jupyter-client (5.2.3)
jupyter-core (4.4.0)
jupyterhub (0.8.1)
jupyterlab (0.32.1)
jupyterlab-launcher (0.10.5)
```

then inside the container i run only `conda install --quiet --yes 'tensorflow=1.0*'`
and after it:
```
pip list | grep jupyter
jupyter-core    4.4.0
```

**Comment by noiseoverip** [comment]
i seems to have successfully installed by replacing `conda` with `pip install tensorflow==1.0.0`, at least jupyter notebook starts but not sure yet if something else will be messed up...

**Comment by jonkrohn** [comment]
Hmm, this is a weird one! I'll keep an eye on it. That replacement of `conda` with `pip install tensorflow` might work fine.

**Comment by jonkrohn** [comment]
Out of curiosity, which LiveLessons are you working through, @noiseoverip ? I might have a more recent, alternate Dockerfile that you could use.

**Comment by noiseoverip** [comment]
planning go trough Deep learning with TensorFlow for now

**Comment by jonkrohn** [comment]
Ah excellent. In that case, another option you have is to use [this Dockerfile](https://github.com/the-deep-learners/deep-learning-illustrated/blob/master/Dockerfile). I think most -- probably all -- of the _Deep Learning with TensorFlow_ notebooks should work without issue.

**Comment by noiseoverip** [comment]
thank, will try that
