### ISSUE TITLE
Issue while following the step by step windows docker installation

### ISSUE THREAD

**Issue by drajesh-tech** [the-deep-learners/TensorFlow-LiveLessons#27]
Hi

   I tried to follow the steps specified in the  link --> TensorFlow-LiveLessons/installation/step_by_step_Windows_Docker_install.md.

  However, I got the following error while executing the step # 7 : When that build process has finished, run the Docker container by executing docker run -v c:/full/path/to/the/clone:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack.

The error message is : 

commad I executed :
  PS D:\Tensor_NLP> docker run -it --rm -p 8888:8888 tensorflow-ll-stack

Error Message I got :

/usr/local/bin/start-notebook.sh: ignoring /usr/local/bin/start-notebook.d/*

Container must be run with group "root" to update passwd file
Executing the command: jupyter notebook
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
ImportError: No module named notebook.notebookapp

Please let me know where I am going wrong.

Thanks Deepa

**Comment by jonkrohn** [comment]
Hi @drajesh-tech ! It appears to be a permissions issue on your machine. 

What happens if you run the same command with `sudo` at the beginning, so `sudo docker run -v c:/full/path/to/the/clone:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack` ?

**Comment by drajesh-tech** [comment]
I get the following error : 

sudo docker run -v d:/Tensor_NLP:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack

sudo : The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sudo docker run -v d:/Tensor_NLP:/home/jovyan/work -it --rm -p 8888:8 ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by drajesh-tech** [comment]
Am working on widows machine and ran the command (the first one that I sent above) on powershell as administrator and got the error that I posted as first post above

Thanks

**Comment by jonkrohn** [comment]
Ah I see. I’m afraid I don’t have access to a Windows machine and don’t
have any personal experience with PowerShell.

It appears the issue is a permissions issue. Either the Administrator
account doesn’t have root access (do Windows machines even have root
access?) or some files don’t have the right root group permissions. I can’t
tell myself.

Perhaps try posting this error in StackOverflow? In the meantime, you can
run all of the notebooks remotely (and for free!) using
colab.research.google.com !
