### ISSUE TITLE
Link to Windows install has changed

### ISSUE THREAD

**Issue by NachtRitter2** [the-deep-learners/TensorFlow-LiveLessons#29]
Link to Windows install should be https://conda.io/projects/conda/en/latest/user-guide/install/windows.html.  Current link https://conda.io/en/latest/user-guide/install/windows.html is invalid.

**Comment by jonkrohn** [comment]
Thank you for identifying this issue, @NachtRitter2 , and for resolving it so quickly, @aevdokimenko 😄
