### ISSUE TITLE
Build docker image

### ISSUE THREAD

**Issue by jhagege** [the-deep-learners/TensorFlow-LiveLessons#34]
Hi, not sure if this repo is still maintained, but didn't succeed to docker build the image. 
I get the following issue: 

> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - numba=0.31

Any idea how to solve ? 
Thanks.

**Comment by jonkrohn** [comment]
Hey there, @jhagege ! 

This repo is for code from the first edition of my *Deep Learning with TensorFlow* videos. I released the second edition this year and [the code is available in this GitHub repo](https://github.com/jonkrohn/DLTFpT/). That repo also includes prominent links to the URLs for the second-edition videos in the O'Reilly online learning platform. Presumably you were accessing the first-edition videos via O'Reilly? 

The second edition contains all of the content from my first edition plus a lot more, so I definitely recommend checking it out. It also contains up-to-date Python libraries so it should resolve your install issue. Please let me know if not :)

**Comment by jhagege** [comment]
Great to here, thanks much :)
