### ISSUE TITLE
DQN learning is very slow in comparison to training video

### ISSUE THREAD

**Issue by jahu** [the-deep-learners/TensorFlow-LiveLessons#35]
Hi, just wondering what might be the issue that the notebook https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/notebooks/cartpole_dqn.ipynb is learning so fast in the training video, whereas whether I run the same notebook on my local machine or colab env with GPU support it is dramatically slower (1 episode per 5s)? In the training video it reaches hundreds of episodes in within seconds.

Thanks in advance for any hints.

**Comment by jonkrohn** [comment]
Hi @jahu! 

This sounds like an issue with a particular library version of Colab -- and perhaps in your local environment as well. When I follow the [installation instructions for this repo](https://github.com/the-deep-learners/TensorFlow-LiveLessons/tree/master/installation) -- or, more specifically, when I use the library versions specified by [the Dockerfile for this repo](https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/Dockerfile) -- the training proceeds extremely quickly. 

In contrast, if I run the notebook in Colab using whatever library versions they have today, then it runs slowly (e.g., 1 episode per 5 seconds) like you're experiencing.

**Comment by jahu** [comment]
Very strange, it seems like keras/tensorflow version issue then...  Thank you very much for the answer @jonkrohn, I will downgrade libs and check performance again.
