### ISSUE TITLE
"No such file or directory: '/opt/conda/bin/python2.7'"

### ISSUE THREAD

**Issue by Adsyarif** [the-deep-learners/TensorFlow-LiveLessons#36]
Do i have install the python ver 2,7 to lean the courses?

**Comment by jonkrohn** [comment]
Hi @Adsyarif, I'd recommend using the updated course [here](https://github.com/jonkrohn/DLTFpT), which uses many updated libraries, including Python 3.7 and TensorFlow 2. Let me know if there's any reason why that's an issue for you.
