### ISSUE TITLE
Migration from Tensorflow 1 to 2

### ISSUE THREAD

**Issue by mrgcohen** [the-deep-learners/TensorFlow-LiveLessons#37]
Do you have a version of these for Tensorflow 2? 

Thanks!

**Comment by jonkrohn** [comment]
Yep @mrgcohen! As noted at the very top of this repo's `Readme.md`, my repo with updated library versions (including TensorFlow 2) is [here](https://github.com/jonkrohn/DLTFpT/). Enjoy!
