### ISSUE TITLE
not found error 'raw_gutenberg_model.w2v'

### ISSUE THREAD

**Issue by abuvaneswari** [the-deep-learners/TensorFlow-LiveLessons#5]
Hello,

I followed the instructions and I am trying to run the example notebook : creating_word_vectors_with_word2vec

All is well until In[22] (model = gensim.models.Word2Vec.load('raw_gutenberg_model.w2v')) where I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'raw_gutenberg_model.w2v'

Please help me fix this.

thanks,
Buvana

**Comment by jonkrohn** [comment]
Hi @abuvaneswari, this is a feature not a bug. 

You need to uncomment the two lines above the line that provided you an error. This will create and save your own `.w2v` file: 

```
model = Word2Vec(sentences=gberg_sents, size=64, sg=1, window=10, min_count=5, seed=42, workers=8)
model.save('raw_gutenberg_model.w2v')
```

Are you following along with the [accompanying videos](https://www.safaribooksonline.com/library/view/deep-learning-for/9780134851921/) to this code notebook? This is detailed there.
