### ISSUE TITLE
Notebook kernel continuously reconnecting

### ISSUE THREAD

**Issue by tomersagi** [the-deep-learners/TensorFlow-LiveLessons#8]
Hi,
I followed the GPU installation instructions on an Ubuntu 16.04 machine with an Nvidia GPU installed properly ( I used it for other things and it seems to work). 

After running the container using

`sudo nvidia-docker run -v ~/Learning/TensorFlow-LiveLessons:/home/jovyan/work -it --rm -p 8888:8888 tfll-gpu-stack`

The kernel connection keeps flashing back and forth between **connected** and **reconnecting** and in the terminal, I'm getting repeated messages of `Adapting to protocol v5.1 for kernel 8039...` with no apparent error message. 

Any ideas how to debug this? This prevents me from running any notebook and properly following your course. 
Thanks
Tomer

**Comment by jonkrohn** [comment]
Hi @tomersagi, I'm afraid this is my first time coming across this error. My recommendation would be to try the [CPU-only install](https://github.com/the-deep-learners/TensorFlow-LiveLessons/tree/master/installation#unix). You don't *need* a GPU for any of the course. Nearly all of the notebooks will complete running within a few minutes on the CPUs alone of most machines.

**Comment by tomersagi** [comment]
Yep, not your fault at all. I tracked it down to my University's Kaspersky anti-virus system. It was blocking the web socket used by jupyter to connect with the kernel. 
Sorry for the bother. Great course BTW!

**Comment by jonkrohn** [comment]
Ah, very well then! I'm glad you're enjoying it, @tomersagi 😃
